# Generated by Django 5.2.4 on 2025-09-01 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('artifact_link', models.URLField(blank=True, null=True)),
                ('outcome_type', models.CharField(blank=True, max_length=100)),
                ('quality_certification', models.CharField(blank=True, max_length=200, null=True)),
                ('commercialization_status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='projects.project')),
            ],
        ),
    ]
