# Generated by Django 5.2.4 on 2025-09-01 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('capabilities', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('inventory_code', models.CharField(blank=True, max_length=120)),
                ('usage_domain', models.CharField(blank=True, max_length=120)),
                ('support_phase', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='facilities.facility')),
            ],
        ),
    ]
