# Generated by Django 5.2.4 on 2025-09-01 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('cross_skill_trained', models.BooleanField(default=False)),
                ('institution', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_project', models.CharField(blank=True, max_length=80)),
                ('skill_role', models.CharField(blank=True, max_length=80)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='participants.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'participant')},
            },
        ),
    ]
