# Generated by Django 5.2.4 on 2025-09-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectParticipant',
        ),
    ]
